# Generated by Django 3.1.2 on 2020-10-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20201026_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='filetb',
            fields=[
                ('filename', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('filedate', models.DateTimeField(auto_now_add=True)),
                ('filepath', models.CharField(max_length=128)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userlogin')),
            ],
            options={
                'db_table': 'filetb',
            },
        ),
    ]
